import type { RequestScenarioTemplate } from "../types";

export const requestScenarioCatalog: RequestScenarioTemplate[] = [
  {
    id: "announcements-benign-library",
    title: "정상 공지 검색 - 도서관",
    category: "announcement",
    expectedClass: "benign",
    expectedOutcome: "allow",
    method: "GET",
    rawUrl: "/api/public/announcements?keyword=%EB%8F%84%EC%84%9C%EA%B4%80&sort=latest&size=5",
    requiresAuth: false,
    notes: "정상적인 공개 공지 검색 요청입니다.",
    source: "built-in",
  },
  {
    id: "board-benign-wifi",
    title: "정상 학생게시판 검색 - 와이파이",
    category: "board-search",
    expectedClass: "benign",
    expectedOutcome: "allow",
    method: "GET",
    rawUrl: "/api/board/posts?keyword=%EC%99%80%EC%9D%B4%ED%8C%8C%EC%9D%B4&sort=latest&size=5",
    requiresAuth: true,
    allowedRoles: ["STUDENT"],
    notes: "학생 게시판의 일반적인 키워드 검색입니다.",
    source: "built-in",
  },
  {
    id: "board-ambiguous-select-notes",
    title: "애매한 검색 - select 문 정리",
    category: "board-search",
    expectedClass: "ambiguous",
    expectedOutcome: "alert",
    method: "GET",
    rawUrl: "/api/board/posts?keyword=select%20%EB%AC%B8%20%EC%A0%95%EB%A6%AC&sort=latest&size=5",
    requiresAuth: true,
    allowedRoles: ["STUDENT"],
    notes: "보안/개발 문맥의 정상 검색이지만 SQL 키워드를 포함합니다.",
    source: "built-in",
  },
  {
    id: "announcement-ambiguous-dot-segment",
    title: "애매한 경로 - 공지 경로 오타",
    category: "path",
    expectedClass: "ambiguous",
    expectedOutcome: "alert",
    method: "GET",
    rawUrl: "/api/public/announcements/..;/",
    requiresAuth: false,
    notes: "오타나 경로 파싱 혼선을 유발하는 요청입니다.",
    source: "built-in",
  },
  {
    id: "board-attacklike-union-search",
    title: "공격성 검색 - union select",
    category: "board-search",
    expectedClass: "attack-like",
    expectedOutcome: "block",
    method: "GET",
    rawUrl: "/api/board/posts?keyword=%27%20union%20select%20password%20from%20users--&sort=latest",
    requiresAuth: true,
    allowedRoles: ["STUDENT"],
    notes: "명확한 SQLi 성격 문자열이 들어간 검색입니다.",
    source: "built-in",
  },
  {
    id: "board-attacklike-script-post",
    title: "공격성 본문 - script 태그 포함",
    category: "post-body",
    expectedClass: "attack-like",
    expectedOutcome: "block",
    method: "POST",
    rawUrl: "/api/board/posts",
    contentType: "application/json",
    body: "{\"title\":\"script 실험\",\"content\":\"<script>alert('x')</script> 패턴 점검용 본문\"}",
    requiresAuth: true,
    allowedRoles: ["STUDENT"],
    notes: "실제 게시글을 생성할 수 있으므로 운영 환경에서는 주의가 필요합니다.",
    source: "built-in",
  },
];
